server:
  port: 8077

spring:
  application:
    name: payment-service
    not_found: 404
    bad_request: 400
    conflict: 409
    ok: 200
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 2
    url: jdbc:postgresql://localhost:5432/payment_service
    username: postgres
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka